### ISSUE TITLE
Simple mistake in build_metric_fn 

### ISSUE THREAD

**Issue by elahehale** [sehunfromdaegu/ECG_JEPA#1]
Hi
Hope you are doing well
In util/perf_metrics.py in function build_metric_fn, I think line 20 should be changed to:
common_metric_fn_kwargs["**num_labels**"] = config["num_labels"]

**Comment by sehunfromdaegu** [comment]
Thank you for your interest in this project.

You are correct—there was a mistake.

I did not notice this issue previously because the ``build_metric_fn`` function is used only during the fine-tuning multi-class process, and I have not performed fine-tuning on multi-label tasks. 

I have just modified it.

Have a great day!
